name = "folfenstein"
version = "0.1.0"
license = "license"
author = "lewis"
maintainer = "lewistmcmillan@gmail.com"
copyright = "Copyright 2023, lewis"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["SDL2", "SDL2_image"]
[dependencies]
fortran-sdl2.git ="https://github.com/interkosmos/fortran-sdl2"

[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

